### ISSUE TITLE
Incompatibility with other mods using ValheimLib.

### ISSUE THREAD

**Issue by PugLyf** [timneill/ValheimMods#1]
When using this mod with other mods utilizing ValheimLib such as CustomBuildingItems by Smallo (https://valheim.thunderstore.io/package/Smallo/CustomBuildingItems/) or Basement by Rolo (https://valheim.thunderstore.io/package/Rolo/Basement/) this error appears in the console.

![image](https://user-images.githubusercontent.com/28744016/114349921-c0763680-9b25-11eb-8b90-ae101daddd1a.png)

**Comment by timneill** [comment]
Does this affect anything loading? I get this error too while running 30~ ish mods but it doesn't affect gameplay. I will investigate in any case but if it's benign then that could be a clue.

On the roadmap is migrating to the combined Jotunn/ValheimLib version once available for the 1.0 release.

**Comment by PugLyf** [comment]
> Does this affect anything loading? I get this error too while running 30~ ish mods but it doesn't affect gameplay. I will investigate in any case but if it's benign then that could be a clue.
> 
> On the roadmap is migrating to the combined Jotunn/ValheimLib version once available for the 1.0 release.

Sorry, I should have been more specific. So with those two mods, I mentioned it makes it so the pieces can't be placed from the hammer's build menu like they are supposed to. I don't know about other cases personally, I just noticed it with other ValheimLib mods such as those.

**Comment by timneill** [comment]
aha ok. which VL mods are you running? i'll install locally and double check for you ASAP

**Comment by PugLyf** [comment]
> aha ok. which VL mods are you running? i'll install locally and double check for you ASAP

At the time it was Basement by Rolo (https://valheim.thunderstore.io/package/Rolo/Basement/), CustomBuildingItems by Smallo (https://valheim.thunderstore.io/package/Smallo/CustomBuildingItems/), and HoneyPlus by OhhLoz (https://valheim.thunderstore.io/package/OhhLoz/HoneyPlus/). Since then I have also added Haemophilia by mugshotsource (https://valheim.thunderstore.io/package/mugshotsource/Haemophilia/), but I haven't tested that one for any incompatibility.

**Comment by timneill** [comment]
Ok I tracked it down to a single blank line in the translations file. I've added an update to Thunderstore. Let me know if everything is back to normal for you.
