### ISSUE TITLE
[Bug, minor] game not showing keybind when trying to sleep

### ISSUE THREAD

**Issue by TNoStone** [timneill/ValheimMods#10]
## Issue:
When looking at the bed to sleep, it does not show the text:
"(PlayerName)'s Bed
(keybind) Sleep"
I understand that this is a minor issue, but I play with someone who struggles with legitimate memory issues and if I put this mod on his computer for our CoOp gameplay, he would struggle with remembering what controller button he needs to press to sleep (and I dont play with a controller so I wouldn't know)

## Config:
> 
> ## Enable this mod
> Enabled = false
> 
> ## Allow multiple people to use this bed simultaneously.
> Multiple bedfellows = false
> 
> ## Sleep at any time of day, not just at night.
> Ignore time restrictions = true
> 
> ## Ignore restrictions for walls and a roof. Sleep under a starry sky.
> Ignore exposure restrictions = false
> 
> ## Enemies no longer prevent you from sleeping.
> Ignore nearby enemies = false
> 
> ## Sleep without a nearby fire.
> Ignore fire requirement = false
> 
> ## Sleep while wet.
> Ignore wet restrictions = false
> 
> ## Sleeping in a bed will not automatically set a spawn point.
> Do not set spawnpoint = false
> 
> ## Sleep without claiming a bed first.
> Do not automatically claim beds = false
> 

## Mod List:

- BepInExPack_Valheim
- Jotunn
- Official_BepInEx_ConfigurationManager
- BetterCreative
- HoneyPlease
- BeehiveUtils_Revived
- Sleepover

**Comment by timneill** [comment]
Thanks for the report. It's probably something small related to it being out of date. I'll take a look

**Comment by timneill** [comment]
hi @TNoStone . there was some weird bug with hover texts. i've rewritten the core part of the mod and can no longer reproduce your issue. (v1.1.0). thanks for the report!
