### ISSUE TITLE
Dream text not displaying, just name of string.

### ISSUE THREAD

**Issue by ate0ate** [timneill/ValheimMods#2]
Love the idea behind this mod btw. I'm playing a rather heavily modded singleplayer game but see no error in the logs or console. Everything works as intended, mostly, but some items appear to only display the string itself rather than the actual text for dreams. I mostly see this particular string, "skald_dream_eikthyr_defeated_02" I am unsure how many others, but this one I have seen three times now.

**Comment by timneill** [comment]
Ok the dream was definitely a fat fingered typo which I've updated.

There was also an issue using ValheimLib regarding loading localizations for runestone texts that I've repaired.

Is everything resolved for you now?

I appreciate you taking the time to report this 👍

**Comment by ate0ate** [comment]
Yes sir, that seems to have done it. I've only played with the update for a couple of hours but so far I have not seen any string names and new dream text is appearing already. Thanks so much for the fix! I will report back if anything odd pops up but it seems to have been resolved so I'll close the issue.
