### ISSUE TITLE
Getting error, mod wont run.

### ISSUE THREAD

**Issue by Vaske1984** [timneill/ValheimMods#3]
Hi i am getting this error:
[Error  :   BepInEx] Could not load [Sleepover 1.0.0] because it has missing dependencies: ValheimModdingTeam.ValheimLib

I am using following mods:
https://valheim.thunderstore.io/package/jpforever/Auto_Feed/
https://valheim.thunderstore.io/package/castix/LootMultiplier/
https://valheim.thunderstore.io/package/virtuaCode/TrashItems/
https://valheim.thunderstore.io/package/LTmadness/TruePause/
https://valheim.thunderstore.io/package/ValheimPlus/ValheimPlus/
https://valheim.thunderstore.io/package/bonesbro_repost/FloorsAreRoofs/

I really like your mod, i hope you can help :) thanks!

**Comment by timneill** [comment]
oh my bad. thats definitely not a dependency. i'll update metadata and deploy a fix for you asap.

**Comment by timneill** [comment]
uploaded a new version to thunderstore. ill update nexus within the next hour. thanks for reporting 👍

**Comment by Vaske1984** [comment]
Thanks a lot <3
