### ISSUE TITLE
Sleepover not working with hearth and home update

### ISSUE THREAD

**Issue by Rhinogames21** [timneill/ValheimMods#4]
Was really interested in using the mod but it's not working for hearth and home update. Are you still updating or if no longer playing would you mind if I tried to get it working? Seems like there a few people would like to use it from nexus mods still.

**Comment by timneill** [comment]
This will be something I will be looking at this month. Thanks for reporting. I'd put Valheim down for a while while waiting for Jotunn + the H&H update. I'm yet to see what they changed for the zone manager, which affects the sleeping rules

**Comment by Rhinogames21** [comment]
Awesome! I'll keep an eye out for updates!

**Comment by timneill** [comment]
New release on nexus and thunderstore should restore previous functionality. the devs added some extra parameters to the `attachStart` method that is called that triggers the sleep animation. updated the call and everything appears to work again.
