### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by Maoman1** [timneill/ValheimMods#5]
One of the dreams said something like "You're sitting at a table and everything is well until fighting breaks out. You make a bet." and 'fighting' is misspelled as 'flyting'. Just wanted to let you know :)

**Comment by timneill** [comment]
Hi @Maoman1 and thanks for the report! It's nice to see people care enough to open issues :)

HOWEVER this is intentional! Flyting is much more fun: https://en.wikipedia.org/wiki/Flyting
