### ISSUE TITLE
[Issue] Claim & spawnpoint

### ISSUE THREAD

**Issue by Bucketsmith** [timneill/ValheimMods#7]
When 'do not claim' and 'do not set spawn' are set to true, there is NO way to do either of those things.
It would be nice if there was some way to still do it. E.g. when crouching.

**Comment by timneill** [comment]
Hi @Bucketsmith. So, if I understand correctly, you are telling the game to not claim or not set spawn for beds, but you want the ability to do that only _sometimes_ ?

**Comment by frankiesek** [comment]
+1 - yes, I want to be able to set spawn point in my base, but do NOT set spawn, when sleeping elsewhere (portable beds for example)

**Comment by timneill** [comment]
@frankiesek @Bucketsmith  thanks for the comments. I've rewritten the core part of the mod to allow more flexibility. It has dedicated keybinds for setting spawn, claiming a bed, and sleeping. it should allow you to do what you want now (v1.1.0). thanks!
