### ISSUE TITLE
public server cannot set spawnpoint on a shared bed.

### ISSUE THREAD

**Issue by codie72** [timneill/ValheimMods#8]
Hi 

We are currently running a public server of valheim and have around 50 players online at any 1 time.
We also have prebuilt structures for people to start out in however, the spawn point is not setting for beds that already have someone on them
we are simply trying to get a saved point for the players, as its a server that never really sleeps 
I noticed on nexus you were having some problems with that feature. i am hoping you have had some luck with this issue?

**Comment by timneill** [comment]
hi @codie72 . sorry for the late reply. i've rewritten the core of the mod and added options for reusing the same spawnpoint. let me know if this is still an issue. i've not tested this on a public server (only locally)
