### ISSUE TITLE
can't seem to find localization file

### ISSUE THREAD

**Issue by GrimmLiberty** [timneill/ValheimMods#9]
Although it is in the directory (spelled correctly and contents not corrupt), it is claiming to not see it: 

[partial log.txt](https://github.com/timneill/ValheimMods/files/10329930/partial.log.txt)

**Comment by GrimmLiberty** [comment]
Log error as of February 2023: 

[Info   :     Skald] Initializing Skald...
[Error  : Unity Log] FileNotFoundException: Could not find file "/home/minecraft/multicraft/servers/server647228/BepInEx/plugins/kinghfb-Skald\localization.language"
Stack trace:
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) (at <695d1cc93cca45069c528c15c9fdd749>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean checkHost) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.StreamReader..ctor (System.String path) (at <695d1cc93cca45069c528c15c9fdd749>:0)
(wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string)
System.IO.File.ReadAllText (System.String path) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Skald.SkaldMod.InitializeSkaldTexts () (at <7b502eab0d854d859dfcbfde10dc8ede>:0)
Skald.SkaldMod.Awake () (at <7b502eab0d854d859dfcbfde10dc8ede>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

**Comment by timneill** [comment]
@GrimmLiberty i updated the way paths are detected, which should be more friendly for cross compatibliity. please reopen this issue if you still have problems. thanks for the report
